# Node.js
strategy:
  matrix:
    node_24_linux:
      node_version: 24.x
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'
- script: |
    node --version
    npm --version
  displayName: 'version check'
- script: |
    npm install
    npm run coverage
  displayName: 'npm install and build'
- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml'